# Config for 'cargo release'
allow-branch = ["main", "master"]
sign-commit = false
sign-tag = false
push = true
publish = false

pre-release-commit-message = "chore: release version {{version}}"
tag-message = "chore: release version {{version}}"
